version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sequential-functions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vn6jgi0d56lp"
s3_prefix = "aws-sequential-functions"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApplicationName=\"Omahdog-AwsSequentialFunctions\" ApiStageName=\"test\""

