AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  Add Three Numbers
  SAM Template for the example of adding three numbers together
Parameters:
  ApplicationName:
    Type: String
    Default: Omahdog-AwsSequentialFunctions
  ApiStageName:
    Type: String
    Default: test
Globals:
  Function:
    Timeout: 6
    CodeUri: dist/
    Runtime: nodejs12.x
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: ApiStageName
      Name:
        Fn::Sub: ${ApplicationName}-ApiGateway
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true
  FlowResultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: ${ApplicationName}-FlowResultTable
  AddNumbersResponseTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-AddNumbersResponseTopic
      DisplayName: Topic for publishing response messages
  AddTwoNumbersRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-AddTwoNumbersRequestTopic
      DisplayName: Topic for sending async AddTwoNumbersRequest messages
  AddThreeNumbersRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-AddThreeNumbersRequestTopic
      DisplayName: Topic for sending async AddThreeNumbersRequest messages
  StoreTotalRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-StoreTotalRequestTopic
      DisplayName: Topic for sending async StoreTotalRequest messages
  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: ${ApplicationName}-FlowInstanceTable
  AddNumbersApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ApplicationName}-AddNumbersApiFunction
      Handler: lambdas.handleAddNumbersApiControllerRoutes
      Environment:
        Variables:
          FUNCTION_NAME:
            Fn::Sub: ${ApplicationName}-AddNumbersApiFunction
          ADD_TWO_NUMBERS_FUNCTION:
            Ref: AddTwoNumbersFunction
          ADD_TWO_NUMBERS_REQUEST_TOPIC:
            Ref: AddTwoNumbersRequestTopic
          ADD_THREE_NUMBERS_REQUEST_TOPIC:
            Ref: AddThreeNumbersRequestTopic
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              Ref: AddTwoNumbersFunction
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - AddTwoNumbersRequestTopic
                - TopicName
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - AddThreeNumbersRequestTopic
                - TopicName
      Events:
        ApiEvent001:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: GET
            Path: /do/add-two-numbers
        ApiEvent002:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: GET
            Path: /do/add-two-numbers/x/{x}/y/{y}
        ApiEvent003:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: POST
            Path: /do/add-two-numbers
        ApiEvent004:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: GET
            Path: /do/add-three-numbers
        ApiEvent005:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: POST
            Path: /do/add-three-numbers
  AddThreeNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ApplicationName}-AddThreeNumbersFunction
      Handler: lambdas.handleAddThreeNumbersRequest
      Environment:
        Variables:
          FUNCTION_NAME:
            Fn::Sub: ${ApplicationName}-AddThreeNumbersFunction
          ADD_NUMBERS_RESPONSE_TOPIC:
            Ref: AddNumbersResponseTopic
          FLOW_INSTANCE_TABLE:
            Ref: FlowInstanceTable
          SUM_NUMBERS_FUNCTION:
            Ref: SumNumbersFunction
          STORE_TOTAL_REQUEST_TOPIC:
            Ref: StoreTotalRequestTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - AddNumbersResponseTopic
                - TopicName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: FlowInstanceTable
        - LambdaInvokePolicy:
            FunctionName:
              Ref: SumNumbersFunction
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - StoreTotalRequestTopic
                - TopicName
      Events:
        SNSEvent001:
          Type: SNS
          Properties:
            Topic:
              Ref: AddThreeNumbersRequestTopic
        SNSEvent002:
          Type: SNS
          Properties:
            Topic:
              Ref: AddNumbersResponseTopic
            FilterPolicy:
              CallbackId:
                - Fn::Sub: ${ApplicationName}-AddThreeNumbersFunction
  AddTwoNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ApplicationName}-AddTwoNumbersFunction
      Handler: lambdas.handleAddTwoNumbersRequest
      Environment:
        Variables:
          FUNCTION_NAME:
            Fn::Sub: ${ApplicationName}-AddTwoNumbersFunction
          ADD_NUMBERS_RESPONSE_TOPIC:
            Ref: AddNumbersResponseTopic
          SUM_NUMBERS_FUNCTION:
            Ref: SumNumbersFunction
      Policies:
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - AddNumbersResponseTopic
                - TopicName
        - LambdaInvokePolicy:
            FunctionName:
              Ref: SumNumbersFunction
      Events:
        SNSEvent001:
          Type: SNS
          Properties:
            Topic:
              Ref: AddTwoNumbersRequestTopic
  SumNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ApplicationName}-SumNumbersFunction
      Handler: lambdas.handleSumNumbersRequest
      Environment:
        Variables:
          FUNCTION_NAME:
            Fn::Sub: ${ApplicationName}-SumNumbersFunction
      Policies: []
      Events: {}
  StoreTotalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ApplicationName}-StoreTotalFunction
      Handler: lambdas.handleStoreTotalRequest
      Environment:
        Variables:
          FUNCTION_NAME:
            Fn::Sub: ${ApplicationName}-StoreTotalFunction
          ADD_NUMBERS_RESPONSE_TOPIC:
            Ref: AddNumbersResponseTopic
          FLOW_RESULT_TABLE:
            Ref: FlowResultTable
      Policies:
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - AddNumbersResponseTopic
                - TopicName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: FlowResultTable
      Events:
        SNSEvent001:
          Type: SNS
          Properties:
            Topic:
              Ref: StoreTotalRequestTopic
Outputs:
  ApiEndpoint:
    Description: API endpoint
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/
  AddTwoNumbersRequestTopicName:
    Description: Name of the topic to which AddTwoNumbersRequest messages are published
    Value:
      Fn::GetAtt:
        - AddTwoNumbersRequestTopic
        - TopicName
  AddNumbersResponseTopicName:
    Description: ARN of the topic on which responses are published
    Value:
      Ref: AddNumbersResponseTopic
