AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Add Three Numbers

  SAM Template for the example of adding three numbers together
  
Parameters:
  ApplicationName:
    Type: String
    Default: Omahdog-AwsSequentialFunctions
  ApiStageName:
    Type: String
    Default: test
        
Globals:
  Function:
    Timeout: 3
    CodeUri: dist/
    Runtime: nodejs12.x

Resources:

  FlowExchangeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-FlowExchangeTopic
      DisplayName: Topic for request & response messages

  FlowDeadLetterQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ApplicationName}-FlowDeadLetterQueueTopic
      DisplayName: Topic for flow dead letter messages

  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${ApplicationName}-FlowInstanceTable

  FlowResultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${ApplicationName}-FlowResultTable

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: ApiStageName
      Name: 
        Fn::Sub: ${ApplicationName}-ApiGateway
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods

  ApiControllerFunction:
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: !Sub ${ApplicationName}-ApiControllerFunction
      Handler: apiControllerLambda.handler
      Environment:
        Variables:
          STORE_TOTAL_FUNCTION_NAME: !Ref StoreTotalFunction
          ADD_THREE_NUMBERS_FUNCTION_NAME: !Ref AddThreeNumbersFunction
          ADD_TWO_NUMBERS_FUNCTION_NAME: !Ref AddTwoNumbersFunction
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
      Policies:
        # TODO: Think about: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#lambda-invoke-policy
        - LambdaInvokePolicy:
            FunctionName: !Ref StoreTotalFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AddThreeNumbersFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AddTwoNumbersFunction
        - SNSPublishMessagePolicy:
            TopicName: 
              Fn::GetAtt: [ FlowExchangeTopic, TopicName ]
      Events:
        AddTwoNumbersByQueryStringEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: GET
            Path: /do/add-two-numbers
        AddTwoNumbersByPathEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: GET
            Path: /do/add-two-numbers/x/{x}/y/{y}
        AddTwoNumbersByBodyEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: POST
            Path: /do/add-two-numbers
        AddThreeNumbersByQueryStringEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: GET
            Path: /do/add-three-numbers
        AddThreeNumbersByBodyEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Method: POST
            Path: /do/add-three-numbers
  
  WireTapFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-WireTapFunction
      Handler: requestLambdas.exchangeWireTapHandler
      Events:
        ExchangeTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
        DeadLetterQueueTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowDeadLetterQueueTopic
  
  DeadLetterQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-DeadLetterQueueFunction
      Handler: requestLambdas.deadLetterQueueHandler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
      Events:
        DeadLetterQueueTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowDeadLetterQueueTopic
  
  AddThreeNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-AddThreeNumbersFunction
      Handler: requestLambdas.addThreeNumbersHandler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowInstanceTable
        - LambdaInvokePolicy:
            FunctionName: !Ref SumNumbersFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StoreTotalFunction
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref FlowDeadLetterQueueTopic
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
          SUM_NUMBERS_FUNCTION_NAME: !Ref SumNumbersFunction
          STORE_TOTAL_FUNCTION_NAME: !Ref StoreTotalFunction
      Events:
        ExchangeTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - AddThreeNumbersRequest:Handler
                - AddThreeNumbersHandler:Response
  
  AddTwoNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-AddTwoNumbersFunction
      Handler: requestLambdas.addTwoNumbersHandler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowInstanceTable
        - LambdaInvokePolicy:
            FunctionName: !Ref SumNumbersFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StoreTotalFunction
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref FlowDeadLetterQueueTopic
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
          SUM_NUMBERS_FUNCTION_NAME: !Ref SumNumbersFunction
          STORE_TOTAL_FUNCTION_NAME: !Ref StoreTotalFunction
      Events:
        ExchangeTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - AddTwoNumbersRequest:Handler
                - AddTwoNumbersHandler:Response
  
  SumNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
        Fn::Sub: ${ApplicationName}-SumNumbersFunction
      Handler: requestLambdas.sumNumbersHandler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: 
              Fn::GetAtt: [ FlowExchangeTopic, TopicName ]
        - DynamoDBCrudPolicy:
            TableName: 
              Ref: FlowInstanceTable
      DeadLetterQueue:
        Type: SNS
        TargetArn: 
          Ref: FlowDeadLetterQueueTopic
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: 
            Ref: FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: 
            Ref: FlowInstanceTable
      Events:
        ExchangeTopic:
          Type: SNS
          Properties:
            Topic: 
              Ref: FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - SumNumbersRequest:Handler
                - SumNumbersHandler:Response
  
  StoreTotalFunction:
    Type: AWS::Serverless::Function
    Properties:
      # The app definition can specify a template for this, referencing any parameters
      FunctionName: 
        Fn::Sub: ${ApplicationName}-StoreTotalFunction
      # The app definition can specify the module name, the method can be derived by convention
      Handler: requestLambdas.storeTotalHandler
      # The app definition will wire up environment variables to the function
      Environment:
        Variables:
          # These will be inferred from the sub-classing of LambdaActivityRequestHandler
          FLOW_EXCHANGE_TOPIC_ARN: 
            Ref: FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: 
            Ref: FlowInstanceTable
          # This will be inferred from the wiring up of the DynamoDb resource access
          FLOW_RESULT_TABLE_NAME: 
            Ref: FlowResultTable
      Policies:
        # LambdaActivityRequestHandler will say it needs the following two resources
        - SNSPublishMessagePolicy:
            TopicName: 
              Fn::GetAtt: [ FlowExchangeTopic, TopicName ]
        - DynamoDBCrudPolicy:
            TableName: 
              Ref: FlowInstanceTable
        # This will be inferred from the wiring up of the DynamoDb resource access
        - DynamoDBCrudPolicy:
            TableName: 
              Ref: FlowResultTable
      Events:
        # The app definition will define that this function is triggered by this event
        ExchangeTopic:
          Type: SNS
          Properties:
            Topic: 
              Ref: FlowExchangeTopic
            FilterPolicy:
              MessageType:
                # Would we ever want to have one of the following, but not the other?
                - StoreTotalRequest:Handler
                - StoreTotalHandler:Response
      DeadLetterQueue:
        Type: SNS
        TargetArn: 
          Ref: FlowDeadLetterQueueTopic

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/"
  