AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  Add Three Numbers
  SAM Template for the example of adding three numbers together
Parameters:
  ApplicationName:
    Type: String
    Default: Omahdog-AwsSequentialFunctions
  ApiStageName:
    Type: String
    Default: test
Globals:
  Function:
    Timeout: 3
    CodeUri: dist/
    Runtime: nodejs12.x
Resources:
  FlowExchangeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-FlowExchangeTopic
      DisplayName: Topic for request & response messages
  FlowDeadLetterQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ApplicationName}-FlowDeadLetterQueueTopic
      DisplayName: Topic for flow dead letter messages
  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: ${ApplicationName}-FlowInstanceTable
  FlowResultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: ${ApplicationName}-FlowResultTable
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: ApiStageName
      Name:
        Fn::Sub: ${ApplicationName}-ApiGateway
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true
  MyFunction:
    Type: AWS::Serverless::Function
Outputs:
  ApiEndpoint:
    Description: API endpoint
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/
