AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Add Three Numbers

  SAM Template for the example of adding three numbers together
  
Parameters:
  ApplicationName:
    Type: String
    Default: Omahdog-AwsSequentialFunctions
  ApiStageName:
    Type: String
    Default: test
        
Globals:
  Function:
    Timeout: 6
    CodeUri: dist/
    Runtime: nodejs12.x

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: ApiStageName
      Name: 
        Fn::Sub: ${ApplicationName}-ApiGateway
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods

  FlowResultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: 
        Fn::Sub: ${ApplicationName}-FlowResultTable

  FlowExchangeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 
        Fn::Sub: ${ApplicationName}-FlowExchangeTopic
      DisplayName: Topic for request & response messages

  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: 
        Fn::Sub: ${ApplicationName}-FlowInstanceTable

Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: 
      Fn::Sub: "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/"
  