AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sequential-functions

  SAM Template for aws-sequential-functions
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  FlowExchangeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub aws-sequential-functions-flow-exchange-topic
      DisplayName: Topic for request & response messages
  
  AddThreeNumbersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: add-three-numbers-function
      CodeUri: dist/
      Handler: AddThreeNumbersFunction.handler
      Runtime: nodejs12.x
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
        # - DynamoDBCrudPolicy:
        #     TableName: !Ref FlowInstanceTable
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
          # FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - AddThreeNumbers:Request
                # - AddThreeNumbers:Response

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AddThreeNumbersFunction:
    Description: "Function to add three numbers together"
    Value: !GetAtt AddThreeNumbersFunction.Arn
  AddThreeNumbersFunctionIamRole:
    Description: "Implicit IAM Role created for AddThreeNumbersFunction"
    Value: !GetAtt AddThreeNumbersFunctionRole.Arn
