AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sequential Functions

  SAM Template for sequential functions example
  
Parameters:
  Application:
    Type: String
    Default: SequentialFunctions
        
Globals:
  Function:
    Timeout: 3

Resources:

  FlowExchangeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Application}-FlowExchangeTopic
      DisplayName: Topic for request & response messages

  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${Application}-FlowInstanceTable

  FlowResultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${Application}-FlowResultTable
  
  WireTapFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-WireTapFunction
      CodeUri: dist/
      Handler: WireTapFunction.handler
      Runtime: nodejs12.x
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
  
  AddThreeNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-AddThreeNumbersFunction
      CodeUri: dist/
      Handler: AddThreeNumbersFunction.handler
      Runtime: nodejs12.x
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowInstanceTable
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - AddThreeNumbersRequest:Handler
                - AddThreeNumbersHandler:Response
  
  SumNumbersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-SumNumbersFunction
      CodeUri: dist/
      Handler: SumNumbersFunction.handler
      Runtime: nodejs12.x
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowInstanceTable
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - SumNumbersRequest:Handler
                - SumNumbersHandler:Response
  
  StoreTotalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Application}-StoreTotalFunction
      CodeUri: dist/
      Handler: StoreTotalFunction.handler
      Runtime: nodejs12.x
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FlowExchangeTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowInstanceTable
        # TODO: How to auto-generate this? The handler would have to expose that it needed such a table
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowResultTable
      Environment:
        Variables:
          FLOW_EXCHANGE_TOPIC_ARN: !Ref FlowExchangeTopic
          FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref FlowExchangeTopic
            FilterPolicy:
              MessageType:
                - StoreTotalRequest:Handler
                - StoreTotalHandler:Response

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WireTapFunction:
    Description: "Function to log all messages published to a topic"
    Value: !GetAtt WireTapFunction.Arn
  AddThreeNumbersFunction:
    Description: "Function to add three numbers together"
    Value: !GetAtt AddThreeNumbersFunction.Arn
  AddThreeNumbersFunctionIamRole:
    Description: "Implicit IAM Role created for AddThreeNumbersFunction"
    Value: !GetAtt AddThreeNumbersFunctionRole.Arn
