AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Add Three Numbers

  SAM Template for the example of adding three numbers together
  
Parameters:
  ApplicationName:
    Type: String
    Default: Omahdog-AwsSequentialFunctions
  ApiStageName:
    Type: String
    Default: test
  # TotalDescription:
  #   Type: String
  #   Default: Aloha from Hawaii
        
Globals:
  Function:
    Timeout: 6
    CodeUri: dist/
    Runtime: nodejs12.x

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: ApiStageName
      Name: 
        Fn::Sub: ${ApplicationName}-ApiGateway
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods

  FlowResultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: 
        Fn::Sub: ${ApplicationName}-FlowResultTable

  AddNumbersResponseTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 
        Fn::Sub: ${ApplicationName}-AddNumbersResponseTopic
      DisplayName: Topic for publishing response messages

  AddTwoNumbersRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 
        Fn::Sub: ${ApplicationName}-AddTwoNumbersRequestTopic
      DisplayName: Topic for sending async AddTwoNumbersRequest messages

  AddThreeNumbersRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 
        Fn::Sub: ${ApplicationName}-AddThreeNumbersRequestTopic
      DisplayName: Topic for sending async AddThreeNumbersRequest messages

  StoreTotalRequestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 
        Fn::Sub: ${ApplicationName}-StoreTotalRequestTopic
      DisplayName: Topic for sending async StoreTotalRequest messages

  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: 
        Fn::Sub: ${ApplicationName}-FlowInstanceTable

Outputs:

  ApiEndpoint:
    Description: "API endpoint"
    Value: 
      Fn::Sub: "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/"

  AddTwoNumbersRequestTopicName:
    Description: "Name of the topic to which AddTwoNumbersRequest messages are published"
    Value:
      Fn::GetAtt: [ AddTwoNumbersRequestTopic, TopicName ]
  # TODO: Add the other request topics
  AddNumbersResponseTopicName:
    Description: "ARN of the topic on which responses are published"
    Value:
      Ref: AddNumbersResponseTopic
  